### ISSUE TITLE
liveglue.js need to cut out anchors too

### ISSUE THREAD

**Issue by nevow-migration** [twisted/nevow#14]
Hi!

I am using Nevow and it's pretty cool. But I encountered a bug with liveglue.js

I am using '#' in hrefs for dynamic contents, so it makes urls like http://host/path#
That is ok, but if user reloads page, liveglue reinitializes and makes all live requests URIs like http://host/path#/livepage_client/... which is completely broken.

Simply added this code to liveglue.js

var anchorIndex = base_url.indexOf('#');
if (anchorIndex != -1) {
  base_url = base_url.substring(0, anchorIndex);
 }

and everything works.

---

Imported from Launchpad using lp2gh.
- date created: 2013-06-10T10:19:04Z
- owner: myautneko
- the launchpad url was https://bugs.launchpad.net/bugs/1189412

**Comment by mithrandi** [comment]
Livepage has been deprecated and removed.
