### ISSUE TITLE
build Nevow without importing Nevow

### ISSUE THREAD

**Issue by nevow-migration** [twisted/nevow#7]
This looks like a good patch:

http://bazaar.launchpad.net/~divmod-dev/divmod.org/build-nevow-without-importing-2699/revision/2601

But why do the execfile hack only when setuptools is present? Why not do that same thing in both cases?

---

Imported from Launchpad using lp2gh.
- date created: 2011-07-18T20:27:58Z
- owner: zooko
- assignee: zooko
- the launchpad url was https://bugs.launchpad.net/bugs/812537

**Comment by zooko** [comment]
Looks like it was https://github.com/twisted/nevow/commit/c9c1939aeb69d2ec48bfa6ea5b616c6bc4a03e2a#diff-2eeaed663bd0d25b7e608891384b7298 that removed the import of the `nevow` package from setup.py.
