### ISSUE TITLE
Nevow uses now-removed FilePath.getmtime(), causes exception

### ISSUE THREAD

**Issue by warner** [twisted/nevow#96]
See [Tahoe-LAFS bug 2846](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/2846). This was caused by the landing of [Twisted-8937](https://twistedmatrix.com/trac/ticket/8937), which removed the (informally) deprecated `getmtime()` method.

This was caught on Tahoe's buildbot, which runs the Tahoe test suite against the trunk version of Twisted.

```
[ERROR]
Traceback (most recent call last):
  File "/home/bb-tahoe/bb-tahoe/deprecations/build/.tox/upcoming-deprecations/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/bb-tahoe/bb-tahoe/deprecations/build/.tox/upcoming-deprecations/local/lib/python2.7/site-packages/nevow/static.py", line 311, in renderHTTP
    if request.setLastModified(self.fp.getmtime()) is http.CACHED:
exceptions.AttributeError: 'FilePath' object has no attribute 'getmtime'

allmydata.test.test_system.SystemTest.test_filesystem
allmydata.test.web.test_web.Web.test_CSS_FILE
```

The fix should be simple: replace `getmtime` with `getModificationTime`, and likewise for any of the other removed FilePath methods.

We're keen to get this fixed, because otherwise our upcoming Tahoe release will stop working as soon as Twisted makes their next release (and they're releasing so quickly these days, that could be rather soon).

**Comment by mithrandi** [comment]
This is failing the Nevow builds against Twisted trunk too, FWIW: https://travis-ci.org/twisted/nevow/builds/182366881

**Comment by mithrandi** [comment]
We should remove the use of these in Nevow, but as noted over at the Twisted bugtracker, these methods were never changed to emit a `DeprecationWarning`, so the change should probably be reverted upstream. I can commit to ensuring a fixed Nevow is released in a timely fashion if the upstream revert doesn't happen, though.

**Comment by warner** [comment]
Awesome, thanks. I'll deprioritize our own bug.. no need for a change in Tahoe now.

**Comment by mithrandi** [comment]
The upstream revert went through, but I could use a review on #97 anyway ;)
